-- Schema for recletters, PostgreSQL flavour.
-- Symlink/copy this file to `1.sql` when running against PostgreSQL.

# --- !Ups

CREATE TABLE call_ (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  label         VARCHAR(255) NOT NULL,
  opens_at      TIMESTAMP,
  deadline      TIMESTAMP    NOT NULL,
  grace_seconds INTEGER      NOT NULL DEFAULT 0,
  site_name_override  VARCHAR(255),
  email_from_override VARCHAR(255),
  is_archived   BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE dossier (
  id           SERIAL       PRIMARY KEY,
  call_id      INTEGER      NOT NULL REFERENCES call_ (id),
  name         TEXT         NOT NULL,
  external_ref TEXT,
  details      TEXT,
  url          TEXT,
  UNIQUE (call_id, external_ref)
);

CREATE INDEX dossier_call_id_idx ON dossier (call_id);
CREATE INDEX dossier_external_ref_idx ON dossier (external_ref);

CREATE TABLE referee_request (
  dossier        INT          NOT NULL REFERENCES dossier (id),
  email          TEXT         NOT NULL,
  details        TEXT,
  role           TEXT,
  status         VARCHAR(16)  NOT NULL DEFAULT 'new'
                 CHECK (status IN ('new','requested','received','declined','cancelled')),
  status_update  TIMESTAMP    NOT NULL DEFAULT NOW(),
  PRIMARY KEY (dossier, email)
);

CREATE TABLE referee_letter (
  dossier  INT       NOT NULL,
  email    TEXT      NOT NULL,
  name     TEXT      NOT NULL,
  letter   BYTEA,
  time     TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (dossier, email),
  FOREIGN KEY (dossier, email) REFERENCES referee_request (dossier, email)
);

CREATE TABLE referee_token (
  dossier       INT       NOT NULL,
  email         TEXT      NOT NULL,
  token_hash    BYTEA     NOT NULL,
  token_issued  TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at    TIMESTAMP NOT NULL,
  PRIMARY KEY (dossier, email),
  FOREIGN KEY (dossier, email) REFERENCES referee_request (dossier, email)
);

CREATE INDEX referee_token_hash_idx ON referee_token (token_hash);

CREATE TABLE users (
  id           SERIAL    PRIMARY KEY,
  email        TEXT      NOT NULL UNIQUE,
  last_name    TEXT,
  first_name   TEXT,
  password     TEXT,
  token_hash   BYTEA,
  token_issued TIMESTAMP,
  CHECK (first_name IS NOT NULL OR last_name IS NOT NULL)
);

# --- !Downs

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS referee_token;
DROP TABLE IF EXISTS referee_letter;
DROP TABLE IF EXISTS referee_request;
DROP TABLE IF EXISTS dossier;
DROP TABLE IF EXISTS call_;
