-- One-shot migration from the legacy (year-based, pgcrypto, native enum) schema
-- to the new (call-based, Scala-side crypto, VARCHAR status) schema.
--
-- Run this on a *copy* of the production PostgreSQL database BEFORE the live
-- cutover, then validate row counts and dossier.call_id correctness.
--
-- Configuration: edit DEADLINE_TEXT below if your historical deadline differs.

BEGIN;

-- 1. Stash the configured deadline string into a temp constant.
\set DEADLINE_TEXT '\'2025-01-15 23:59:59\''

-- 2. Create the new tables alongside the legacy ones (they must not exist yet).
CREATE TABLE call_ (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(64)  NOT NULL UNIQUE,
  label         VARCHAR(255) NOT NULL,
  opens_at      TIMESTAMP,
  deadline      TIMESTAMP    NOT NULL,
  grace_seconds INTEGER      NOT NULL DEFAULT 0,
  site_name_override  VARCHAR(255),
  email_from_override VARCHAR(255),
  is_archived   BOOLEAN      NOT NULL DEFAULT FALSE
);

-- 3. One call row per pre-existing distinct year. Adjust the slug/label
--    prefix to whatever names your historical site used.
\set CALL_SLUG_PREFIX  '\'call-\''
\set CALL_LABEL_PREFIX '\'Call \''

INSERT INTO call_ (slug, label, deadline)
SELECT
  :CALL_SLUG_PREFIX  || year::text,
  :CALL_LABEL_PREFIX || year::text,
  :DEADLINE_TEXT::timestamp
FROM (SELECT DISTINCT year FROM dossier) y
ORDER BY year;

-- 4. Add the new columns to dossier and backfill from year/details.
ALTER TABLE dossier ADD COLUMN call_id      INTEGER REFERENCES call_ (id);
ALTER TABLE dossier ADD COLUMN external_ref TEXT;

UPDATE dossier d
SET    call_id = c.id
FROM   call_ c
WHERE  c.slug = :CALL_SLUG_PREFIX || d.year::text;

-- The legacy HotCRP feed put the paperId into details. If your deployment used
-- details for genuine notes instead, comment this block out.
UPDATE dossier
SET    external_ref = details,
       details      = NULL
WHERE  details ~ '^[0-9]+$';

ALTER TABLE dossier ALTER COLUMN call_id SET NOT NULL;
ALTER TABLE dossier DROP COLUMN year;
CREATE UNIQUE INDEX dossier_call_external_idx ON dossier (call_id, external_ref);

-- 5. Convert referee_request.status from native enum to VARCHAR(16) + CHECK.
ALTER TABLE referee_request
  ALTER COLUMN status TYPE VARCHAR(16) USING status::text;
ALTER TABLE referee_request
  ADD CONSTRAINT referee_request_status_chk
    CHECK (status IN ('new','requested','received','declined','cancelled'));

ALTER TABLE referee_request ADD COLUMN role TEXT;

DROP TYPE request_status;

-- 6. Convert referee_token from plaintext to SHA-256 hash, add expires_at.
--    Existing tokens are invalidated (deleted) because we never stored the
--    plaintext anywhere else; users requesting a letter after the cutover get a
--    fresh token via sendRequestEmails.
DELETE FROM referee_token;
ALTER TABLE referee_token DROP COLUMN token;
ALTER TABLE referee_token ADD COLUMN token_hash BYTEA NOT NULL;
ALTER TABLE referee_token ADD COLUMN expires_at TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '90 days');
ALTER TABLE referee_token ALTER COLUMN expires_at DROP DEFAULT;
CREATE INDEX referee_token_hash_idx ON referee_token (token_hash);

-- 7. Convert users.token from pgcrypto-hashed text to BYTEA SHA-256, rename column.
ALTER TABLE users ADD COLUMN token_hash BYTEA;
UPDATE users SET token_hash = token::bytea WHERE token IS NOT NULL;
ALTER TABLE users DROP COLUMN token;

-- 8. (Optional) Drop the pgcrypto extension if no other app in the DB needs it.
-- DROP EXTENSION pgcrypto;

-- 9. Record this evolution as already applied so Play does not try to re-apply it.
CREATE TABLE IF NOT EXISTS play_evolutions (
  id                 INTEGER NOT NULL PRIMARY KEY,
  hash               VARCHAR(255) NOT NULL,
  applied_at         TIMESTAMP    NOT NULL,
  apply_script       TEXT,
  revert_script      TEXT,
  state              VARCHAR(255),
  last_problem       TEXT
);
INSERT INTO play_evolutions (id, hash, applied_at, state)
  VALUES (1, 'manual-migration', NOW(), 'applied')
  ON CONFLICT (id) DO NOTHING;

COMMIT;
